### ISSUE TITLE
华为服务解析列表有问题

### ISSUE THREAD

**Issue by cyacg** [gamekingv/docker-drive#1]
![image](https://user-images.githubusercontent.com/48150476/115398600-e84a5600-a219-11eb-8617-be4e821c1719.png)

**Comment by gamekingv** [comment]
华为云我没用过，是怎么创建镜像仓库的，在界面上没看到有相关操作。另外记得不要和xausky/DockerRegisterCloud混用，会破坏其配置文件。

**Comment by cyacg** [comment]
华为云
https://console.huaweicloud.com/swr/
没有20分钟的限制

**Comment by gamekingv** [comment]
我更新了一下，你试试最新版，测试下来有一个问题就是华为云不能删除最后一个文件，删除时会报错，还没想到怎么解决。

**Comment by cyacg** [comment]
华为云可以使用了，阿里云国际的不行了
![P9%5R`TD)X01RA@AJT{XZGD](https://user-images.githubusercontent.com/48150476/115539417-8b10dc00-a2cf-11eb-88c5-359926fec487.jpg)

**Comment by gamekingv** [comment]
再试试，太久没用阿里云甚至触发了一个存在已久的bug

**Comment by cyacg** [comment]
可以了
